### ISSUE TITLE
Running LV2019 SP1 and cant install since library is LV2020

### ISSUE THREAD

**Issue by antneewills** [MediaMongrels-Ltd/LabVIEW-Secure-WebSockets-Addon#1]
I installed you standard websockets library via VI package manager for LabVIEW 2019 SP1, but my VI package manager cannot see the secure websockets addon nor can I install this version in my LabVIEW 2019 SP1 since it is written in 2020. Will there be a version released to support 2019? How can I install?

**Comment by samsharp99** [comment]
The WSS addon package uses new functionality provided in LabVIEW 2020. It will not work or be supported in earlier versions of LabVIEW as the Secure Socket/TLS functionality is not available in those versions.
